"""
.. module:: debug_main_controller.py
    :platform: MacOS, Unix, Windows,
    :synopsis: A helper script to read a .csv file generated by 
    debug_main_controller.c and plot
.. moduleauthor:: Pavlo Vlastos <pvlastos@ucsc.edu>
"""

from numpy import loadtxt
import numpy as np
import matplotlib.pyplot as plt
import csv

###############################################################################
path = './debug_main_controller.csv'
with open(path, 'r') as f:
    reader = csv.reader(f, delimiter=',')
    headers = next(reader)
    data = np.array(list(reader)).astype(float)

print(headers)

print("data.shape: {}".format(data.shape))

t = data[:, 0]
psi = data[:, 1]
r = data[:, 2]
x = data[:, 3]
y = data[:, 4]
v = data[:, 5]
u = data[:, 6]
u_pulse = data[:, 7]

print("x.shape: {}".format(x.shape))
print("y.shape: {}".format(y.shape))

waypoints = np.array([
    [0.0, 5.0],
    [20.0, 5.0],
    [0.0, 25.0],
    [10.0, 25.0],
    [20.0, 15.0]
])

###############################################################################
# Plot positon data
plt.figure()

ax = plt.gca()
ax.plot(waypoints[:, 0], waypoints[:, 1], color='black')

# Waypoints
ax.scatter(waypoints[:, 0], waypoints[:, 1],
            color='yellow',
            label='Waypoints',
            marker='v',
            edgecolors='black', zorder=10)
ax.plot(x, y)
plt.scatter(x[0], y[0],
                color='lime',
                label='Start',
                marker='o',
                edgecolors='black', zorder=10)
plt.scatter(x[-1], y[-1],
            color='red',
            label='End',
            marker='s',
            edgecolors='black', zorder=10)

plt.grid()
plt.show()

###############################################################################
# Plot u (servo) pulse
plt.figure()

ax = plt.gca()
ax.plot(t, u)
ax.plot(t, u_pulse)

plt.grid()
plt.show()