"""
.. module:: plot_mav_csv.py
	:platform: MacOS, Unix, Windows,
	:synopsis: Plot data in csv's generated by mavcsv_logging.py
.. moduleauthor:: Pavlo Vlastos <pvlastos@ucsc.edu>
"""
import numpy as np
import matplotlib.pyplot as plt
import csv

import argparse

###############################################################################
# Parse Arguments
###############################################################################
parser = argparse.ArgumentParser()

parser.add_argument('mav_csv_log', nargs='?',
                    default='{}.csv'.format())
